### PR TITLE
Add SCRAM-SHA-1, SCRAM-SHA-256 and SCRAM-SHA512 auth

### PR DESCRIPTION
**Pull request by mdosch**
- Add SCRAM-SHA-1, SCRAM-SHA-256 and SCRAM-SHA512 auth

### CODE REVIEW

**Comment by Neustradamus** [comment]
@mdosch: Excellent, good job!

Can you add SCRAM-SHA-256 and SCRAM-SHA-512 and SCRAM-SHA3-512 too?

-PLUS variants are impossible?

**Comment by mdosch** [comment]
I have some code for scram-sha-256 and scram-sha-512 locally, but I was not able to test it yet. Once I'm done I'll finish this PR.
-PLUS is probably not impossible but I had no time for this yet.

**Comment by Neustradamus** [comment]
@mdosch: Okay! :)
For me, SCRAM support is the current giant missing feature!

cc: @mattn.

**Comment by mdosch** [comment]
I don't think it is necessary to ping mattn all the time. This PR is not yet finished and it's only creating noise in their inbox. Keep calm. 🙂

**Comment by Neustradamus** [comment]
Replaced by:
- https://github.com/mattn/go-xmpp/pull/147

**Pull request closed without merging**
