### PR TITLE
Add Status into Presence struct

### PR DESCRIPTION
**Pull request by chteufleur**
I just add the status into the Presence structure.

### CODE REVIEW

**Comment by mattn** [comment]
go fmt please

**Comment by chteufleur** [comment]
Sorry, I don't know what do you mean with "go fmt" ?

**Comment by mattn** [comment]
Just type `go fmt` on the directory :)

**Comment by chteufleur** [comment]
Ok, didn't know about this command line. Pretty useful.
Thank.

**Comment by mattn** [comment]
Thanks.

**Pull request merged**
