### PR TITLE
Add SCRAM PLUS variants.

### PR DESCRIPTION
**Pull request by mdosch**

### CODE REVIEW

**Comment by mattn** [comment]
Thank you

**Comment by mdosch** [comment]
Thank you for merging. :)

**Comment by Neustradamus** [comment]
@mdosch: Good job, thanks for your PR and @mattn for merging!

Linked to:
- https://github.com/mattn/go-xmpp/pull/147
- https://github.com/scram-sasl/info/issues/1

**Comment by Neustradamus** [comment]
@mattn: Please plan a new build with this important feature!

**Pull request merged**
