### PR TITLE
Proposed changes:

### PR DESCRIPTION
**Pull request by ikq**
1. o.Debug print not only received, but also sent data. 
   Using standard log. (So each log entry synchronized, and log can be reassigned to file)
2. changed startTLSIfRequired switch. 
   Can be used connection without TLS:
   xmpp.Options {NoTLS: true, StartTLS: false, InsecureAllowUnencryptedAuth: true}
3. clientIQ used pointer to bindBind (Because bindBind is optional)
4. init(): session use different id (not the same as bind). 
           added waiting iq session response (I found it important to Tigase XMPP server, 
   otherwise it receive presence and did not answer to iq session)

### CODE REVIEW

**Comment by ikq** [comment]
Opps. I want update my clone of the library, but by mistake update also the pull request
(that seems already is too complicated).
So I revert it.

**Comment by mattn** [comment]
I don't make sure what you mean the change. Is that issue of this repository? Then, could you please send me pull-request?

**Comment by ikq** [comment]
I'm very happy with your repository. Thanks.

I don't think you should add to your repository new change (that I already reverted)

It's not fix of issues, but example that your library is extendable, and programmer can easy add new custom XMPP extensions.

I added to XMPP message parser (ClientMessage), the XMPP extensions:
- <server-ack xmlns="urn:audiocodes:ack"/> // Custom XMPP extension of my firm.
-  <request xmlns="urn:xmpp:receipts"/>       // It's XEP-0184
-  <received xmlns='urn:xmpp:receipts'>

I'm also made changes in Debug options that can skip XMPP messages during session opening.
It  help me in debug, but add too much complexity to the library.

**Comment by mattn** [comment]
Sorry long delay. Could you please fix conflict?

**Comment by ikq** [comment]
Hmm... I'm completely forgot my proposed change. 
Seems it was example that library can be extended. Not something serious...

**Comment by Neustradamus** [comment]
@mdosch: What do you think?

@ikq: Why have you closed your PR?

**Comment by ikq** [comment]
Hi, passed 8 years. ;-) 
At time of writing I suppose it was a  relevant  PR.
I'm off topic now (not use XMPP and rarely use Go).

**Pull request closed without merging**
